---
repository:
  name: pipelines
  description: A template repo for repo settings
  homepage: https://pipelines.irishlab.io/
  allow_auto_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  auto_init: true
  default_branch: main
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  is_template: false
  license_template: mit
  private: false
  security_and_analysis:
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled

environments:
  - name: prod
    wait_timer: 0

branches:
  - name: default
    protection:
      enforce_admins: true
      required_pull_request_reviews: true
      required_status_checks:
        strict: true
