---
repository:
  auto_init: true
  license_template: mit
  name: pipelines
  description: A template repo for repo settings
  homepage: https://pipelines.irishlab.io/
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  is_template: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  security_and_analysis:
    advanced_security:
      status: enabled
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled

collaborators:
  - username: irish1986
    permission: admin

branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_signatures: true
        require_linear_history: false
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
