---
    name: Run pre-commit
    
    on: # yamllint disable-line rule:truthy
      workflow_dispatch:
      workflow_call:
    
    jobs:
      pre-commit:
        name: Pre-Commit
        runs-on: ubuntu-22.04
        timeout-minutes: 5
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.7
    
          - name: Run Pre-Commit
            uses: pre-commit/action@v3.0.1
