---
    name: Run pre-commit
    
    on: # yamllint disable-line rule:truthy
      workflow_dispatch:
      workflow_call:
    
    jobs:
      pre-commit:
        name: Pre-Commit
        runs-on: ubuntu-22.04
        timeout-minutes: 5
        strategy:
          matrix:
            PYTHON_VERSION: # https://devguide.python.org/versions/
              - "3.11"
              - "3.12"
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.7
    
          - name: Setup Python ${{ matrix.PYTHON_VERSION }}
            uses: actions/setup-python@v5.1.0
            with:
              python-version: ${{ matrix.PYTHON_VERSION }}
              cache: 'pip' # caching pip dependencies
    
          - name: Run Pre-Commit
            uses: pre-commit/action@v3.0.1
