---
name: Hello World

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  # This workflow contains a single job called "build"
  hello-world:
    name: Hello World - A testing workflow
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
