name: Reusable workflow

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - id: step1
        run: echo "hello world"
