name: Reusable workflow

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  reusable_workflow:
    name: Reusable workflow
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Hello World
        run: |
          echo "hello world"
